# Generated by Django 2.2.6 on 2019-10-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbanews',
            name='posttime',
            field=models.CharField(max_length=100),
        ),
    ]
